# Application Core Configuration
spring:
  application:
    name: banking-app
    version: 1.0.0

  # Security Configuration
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:f2bfa532ce2c248ef8b92b1bcf31cad8014bb40e633c01a7a720e5d6474b8f3d}
      expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds

  # Profile-specific configuration
  profiles:
    active: ${SPRING_PROFILE:development}

  # Datasource Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:banking-app}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA and Hibernate Configuration
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true

    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}

    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Africa/Nairobi
        dialect:


# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api/v1
  compression:
    enabled: true

# Custom Application Properties
app:
  security:
    cors:
      allowed-origins:
        - http://localhost:4200
        - https://banking-app.mywebsite.com

  feature-flags:
    account-creation: ${ACCOUNT_CREATION_ENABLED:true}
    notification-service: ${NOTIFICATION_SERVICE_ENABLED:true}
    fraud-detection: ${FRAUD_DETECTION_ENABLED:false}

# Environment-Specific Profiles
---
spring:
  config:
    activate:
      on-profile: development
  datasource:
    url: jdbc:mysql://localhost:3306/banking-dev

---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    url: jdbc:mysql://prod-db.mywebsite.com:3306/banking-prod
  jpa:
    hibernate:
      ddl-auto: validate